name: "techatlas"
description: "Akilli Tahta Projesi."
publish_to: "none"
version: "0.0.51"
environment:
  sdk: "^3.9.2"
dependencies:
  flutter:
    sdk: "flutter"
  cupertino_icons: "^1.0.8"
  provider: ^6.1.5+1
  pdfrx: ^1.0.88
  http: "^1.2.2"
  path_provider: "^2.1.5"
  window_manager: "^0.5.1"
  inno_build: "^0.4.0"
  archive: ^3.4.0
  package_info_plus: ^9.0.0
  flutter_colorpicker: ^1.1.0
  screen_retriever: ^0.2.0
  flutter_resizable_container: ^4.2.0
  flutter_box_transform: ^0.4.7
  icons_flutter: ^0.0.5
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1
  file_picker: ^8.1.6
  path: ^1.9.0
  image: ^4.0.17
  universal_io: ^2.3.1
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  vector_math: ^2.1.4
  ffi: ^2.1.4
  win32: ^5.15.0
  msix: ^3.16.12
  encrypt: ^5.0.3
  video_player: ^2.9.2
  video_player_win: ^2.0.0
  chewie: ^1.8.5
  math_expressions: ^3.1.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  translator: ^1.0.4+1
  audioplayers: ^6.5.1
  flutter_tts: 4.0.2
dev_dependencies:
  flutter_test:
    sdk: "flutter"
  flutter_lints: "^5.0.0"
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 256

flutter_native_splash:
  color: "#000000"
  image: assets/logo.png
flutter:
  uses-material-design: true
  assets:
    - assets/service_account.enc
    - assets/logo.png

msix_config:
  display_name: TechAtlas
  publisher_display_name: TechAtlas
  identity_name: com.techatlas.app
  msix_version: 1.0.0.0
  logo_path: windows\runner\resources\app_icon.ico
  capabilities: internetClient, privateNetworkClientServer
  publisher: CN=TechAtlas
